### ISSUE TITLE
Executive Summary

### ISSUE THREAD

**Issue by germonprez** [knguyen94/ManagingITTeam#17]
Fix typos and grammatical errors in the Executive Summary. These exist throughout. 

Make all the text consistent. Why have some text in grey boxes and some not in grey boxes? 

Provide a richer description of the problem. This stems from developers being able to bring external source into the organization with very few checks (problem). The solution is to create an automated system that will check this incoming software.

**Comment by knguyen94** [comment]
I will go over the document and correct the mistakes.

**Comment by ghost** [comment]
Edited
