### ISSUE TITLE
Use Case Comments

### ISSUE THREAD

**Issue by germonprez** [knguyen94/ManagingITTeam#19]
You actually have four use cases (you have a second number 2)

The use cases (first)2 and 3 are more about setting up the system. The use cases should be more about the use of the system. For example, installing a DB is not about use. 

A few sample uses could be
- What you have for your second use case 2. 
- Developer required to post source online (license mandated)
- Manager checks results against corporate policy 

Focus these more on use, not installation.

**Comment by ghost** [comment]
fixed
