### ISSUE TITLE
Final Walk through - Each person verifies and commits changes

### ISSUE THREAD

**Issue by knguyen94** [knguyen94/ManagingITTeam#40]

**Comment by knguyen94** [comment]
I have visually inspected all items and find them to be good. I have changed errors that i spotted.

**Comment by jaredpelzer** [comment]
I checked through them all and made my changes. They all look good to me.

**Comment by ghost** [comment]
I've walked through mine and everything looks ok

**Comment by jaredpelzer** [comment]
If everyone is in agreement with the documents, I will email Matt our link at 8:00 pm

**Comment by knguyen94** [comment]
I'm in agreement with that idea.

**Comment by ghost** [comment]
fine by me
