### ISSUE TITLE
Add more content

### ISSUE THREAD

**Issue by knguyen94** [knguyen94/ManagingITTeam#6]
Need to communicate more and add more content!

**Comment by ghost** [comment]
Ill add some more cases either tonight or tomorrow. How many do you want me to add?

**Comment by jaredpelzer** [comment]
Justin, good work on the cases. I will update the DFD, Definitions, and Presentation Slides by tonight.

**Comment by ghost** [comment]
What else do you want me to do

**Comment by jaredpelzer** [comment]
If you could finish the executive summary, that would be awesome

**Comment by ghost** [comment]
Ok

**Comment by knguyen94** [comment]
Sorry guys,

I've been way out of the area unable to get to this. What would you like me
to work on. Sorry for not contributing much but I have been working pass
few weeks with no time off.

Again sorry,

Khoi Nguyen

**Comment by jaredpelzer** [comment]
Khoi, let me know if you can finish the ERD. There were a couple lectures on the subject. Let me know if/when you can get that done and I can help you get the image on the document.

**Comment by knguyen94** [comment]
I will take a look at it tonight!
